{% set version = "2.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-timetk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/timetk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/timetk/timetk_{{ version }}.tar.gz
  sha256: 6f5c47dd51a9632a1270debbe080740cf5d61f347332e68c6c1ec47ee333dbb8

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-anytime
    - r-assertthat
    - r-dplyr >=1.0.0
    - r-forcats
    - r-forecast
    - r-generics
    - r-ggplot2
    - r-hms
    - r-lubridate >=1.6.0
    - r-padr >=0.5.2
    - r-plotly
    - r-purrr >=0.2.2
    - r-readr >=1.3.0
    - r-recipes >=1.0.4
    - r-rlang >=0.4.11
    - r-rsample
    - r-slider
    - r-stringi >=1.4.6
    - r-stringr
    - r-tibble >=3.0.3
    - r-tidymodels
    - r-tidyr >=1.1.0
    - r-tidyselect >=1.1.0
    - r-timedate
    - r-timeseries
    - r-tsfeatures
    - r-xts >=0.9_7
    - r-zoo >=1.7_14
  run:
    - r-base
    - r-anytime
    - r-assertthat
    - r-dplyr >=1.0.0
    - r-forcats
    - r-forecast
    - r-generics
    - r-ggplot2
    - r-hms
    - r-lubridate >=1.6.0
    - r-padr >=0.5.2
    - r-plotly
    - r-purrr >=0.2.2
    - r-readr >=1.3.0
    - r-recipes >=1.0.4
    - r-rlang >=0.4.11
    - r-rsample
    - r-slider
    - r-stringi >=1.4.6
    - r-stringr
    - r-tibble >=3.0.3
    - r-tidymodels
    - r-tidyr >=1.1.0
    - r-tidyselect >=1.1.0
    - r-timedate
    - r-timeseries
    - r-tsfeatures
    - r-xts >=0.9_7
    - r-zoo >=1.7_14

test:
  commands:
    - $R -e "library('timetk')"           # [not win]
    - "\"%R%\" -e \"library('timetk')\""  # [win]

about:
  home: https://github.com/business-science/timetk
  license: GPL-3.0-or-later
  summary: "Get the time series index (date or date-time component), time series signature (feature extraction of date or date-time component for time series machine learning), and time series summary (summary attributes about time series). Create future time series based on properties of existing time series index using
    logistic regression. Coerce between time-based tibbles ('tbl') and 'xts', 'zoo', and 'ts'. Methods discussed herein are commonplace in machine learning, and have been cited in various literature. Refer to \"Calendar Effects\" in papers such as Taieb, Souhaib Ben. \"Machine learning strategies for multi-step-ahead time
    series forecasting.\" Universit Libre de Bruxelles, Belgium (2014): 75-86. <http://souhaib-bentaieb.com/pdf/2014_phd.pdf>."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - mxr-conda
    - conda-forge/r
    - oblute
    - rluria14
    - benhuff
