{% set version = "2.8.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-timetk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/timetk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/timetk/timetk_{{ version }}.tar.gz
  sha256: 0ec00f927bd678f74c3370e62c77857ba88727133c253065ad9f6abfb81c09dd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-anytime
    - r-assertthat
    - r-dplyr >=1.0.0
    - r-forcats
    - r-forecast
    - r-generics
    - r-ggplot2
    - r-hms
    - r-lubridate >=1.6.0
    - r-padr >=0.5.2
    - r-plotly
    - r-purrr >=0.2.2
    - r-readr >=1.3.0
    - r-recipes >=0.1.4
    - r-rlang >=0.4.7
    - r-rsample
    - r-slider
    - r-stringi >=1.4.6
    - r-stringr
    - r-tibble >=3.0.3
    - r-tidyr >=1.1.0
    - r-tidyselect >=1.1.0
    - r-timedate
    - r-tsfeatures
    - r-xts >=0.9_7
    - r-zoo >=1.7_14
  run:
    - r-base
    - r-anytime
    - r-assertthat
    - r-dplyr >=1.0.0
    - r-forcats
    - r-forecast
    - r-generics
    - r-ggplot2
    - r-hms
    - r-lubridate >=1.6.0
    - r-padr >=0.5.2
    - r-plotly
    - r-purrr >=0.2.2
    - r-readr >=1.3.0
    - r-recipes >=0.1.4
    - r-rlang >=0.4.7
    - r-rsample
    - r-slider
    - r-stringi >=1.4.6
    - r-stringr
    - r-tibble >=3.0.3
    - r-tidyr >=1.1.0
    - r-tidyselect >=1.1.0
    - r-timedate
    - r-tsfeatures
    - r-xts >=0.9_7
    - r-zoo >=1.7_14

test:
  commands:
    - $R -e "library('timetk')"           # [not win]
    - "\"%R%\" -e \"library('timetk')\""  # [win]

about:
  home: https://github.com/business-science/timetk
  license: GPL-3.0-or-later
  summary: "Get the time series index (date or date-time component), time series signature (feature extraction of date or date-time component for time series machine learning), and time series summary (summary attributes about time series). Create future time series based on properties of existing time series index using\
    \ logistic regression. Coerce between time-based tibbles ('tbl') and 'xts', 'zoo', and 'ts'. Methods discussed herein are commonplace in machine learning, and have been cited in various literature. Refer to \"Calendar Effects\" in papers such as Taieb, Souhaib Ben. \"Machine learning strategies for multi-step-ahead time\
    \ series forecasting.\" Universit Libre de Bruxelles, Belgium (2014): 75-86. <http://souhaib-bentaieb.com/pdf/2014_phd.pdf>."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - mxr-conda
    - conda-forge/r
    - oblute
    - rluria14
    - benhuff

# The original CRAN metadata for this package was:
# Package: timetk
# Type: Package
# Title: A Tool Kit for Working with Time Series
# Version: 0.1.2
# Date: 2019-09-21
# Authors@R: c( person("Matt", "Dancho", email = "mdancho@business-science.io", role = c("aut", "cre")), person("Davis", "Vaughan", email = "dvaughan@business-science.io", role = c("aut")) )
# Description: Get the time series index (date or date-time component), time series signature (feature extraction of date or date-time component for time series machine learning), and time series summary (summary attributes about time series). Create future time series based on properties of existing time series index using logistic regression. Coerce between time-based tibbles ('tbl') and 'xts', 'zoo', and 'ts'. Methods discussed herein are commonplace in machine learning, and have been cited in various literature. Refer to "Calendar Effects" in papers such as Taieb, Souhaib Ben. "Machine learning strategies for multi-step-ahead time series forecasting." Universit Libre de Bruxelles, Belgium (2014): 75-86. <http://souhaib-bentaieb.com/pdf/2014_phd.pdf>.
# URL: https://github.com/business-science/timetk
# BugReports: https://github.com/business-science/timetk/issues
# License: GPL (>= 3)
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.3.0)
# Imports: dplyr (>= 0.7.0), lazyeval (>= 0.2.0), lubridate (>= 1.6.0), padr (>= 0.3.0), purrr (>= 0.2.2), readr (>= 1.0.0), stringi (>= 1.1.5), tibble (>= 1.2), tidyr (>= 0.6.1), xts (>= 0.9-7), zoo (>= 1.7-14)
# Suggests: tidyverse, broom, forcats, forecast, knitr, rmarkdown, robets, scales, stringr, testthat, tidyquant, fracdiff, timeDate, timeSeries, tseries
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-09-25 10:53:22 UTC; mdancho
# Author: Matt Dancho [aut, cre], Davis Vaughan [aut]
# Maintainer: Matt Dancho <mdancho@business-science.io>
# Repository: CRAN
# Date/Publication: 2019-09-25 13:50:02 UTC
# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
